import { type NextPage } from "next";
import { Input } from "~/components/Input";
import { FormGroup } from "~/components/FormGroup";
import Head from "next/head";
import { useState } from 'react'; 

const GeneratePage: NextPage = () => {

    //States
    const [form, setForm] = useState({
        prompt: "",
    }); 

    //Update form function
    function updateForm(key: string) {
        return function(e: React.ChangeEvent<HTMLInputElement>){
            setForm((prev) => ({
                ...prev,
                [key]: e.target.value
            }))
        }
    }

    //Handle form submit 
    function handleFormSubmit(e: React.FormEvent){
        e.preventDefault();
    }

  return (
    <>
      <Head>
        <title>Generate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form className="flex flex-col gap-2"
            onSubmit={handleFormSubmit}
        >
            <FormGroup>
                <label>Prompt</label>
                <Input value={form.prompt} onChange={(updateForm("prompt"))}/>
            </FormGroup>
            <button className="bg-blue-400 hover:bg-blue-500 px-4 py-2 rounded">Submit</button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
